### ISSUE TITLE
Info about supported protocols as well as IP with port needed

### ISSUE THREAD

**Issue by sebastiankb** [thingweb/node-wot#10]
needed for TD generation. Should be available in ExposedThing or Servient class.

**Comment by h0ru5** [comment]
we could change the getPort of ProtocolServer into getHostPart()

WDYT?

**Comment by mkovatsc** [comment]
The port is good debug information. Instead of merging it into a string and then having to dissect it again, I would rather provide all three interfaces:
- getPost()
- getHost()
- getAuthority() - nutzt getPost() und getHost(), um den Authority Teil der URI zurückzugeben

Ich befürchte das gibt noch wildcard/IPv4/IPv6 Kopfschmerzen und wir brauchen mehrere Server vom gleichen Typ...
