### ISSUE TITLE
Improper error handling while providing each Sandbox the Scheduling functions

### ISSUE THREAD

**Issue by farshadahmadi** [thingweb/node-wot#103]
Each sandbox is provided with Scheduling functionalities like `setTimeout `and `setInterval `:

```
         let context = vm.createContext({
            'WoT': new WoTImpl(this),
            'console': console,
            'setInterval': setInterval,
            'setTimeout': setTimeout
        });
```

These functionalities can throw asynchronous errors. The current error handling mechanism is only capable of handling synchronous errors:

```
        try {
            script.runInContext(context, options);
        } catch (err) {
            let scriptPosition = err.stack.match(/at evalmachine\.<anonymous>\:([0-9]+\:[0-9]+)\n/)[1];
            console.error(`Servient caught error in privileged '${filename}' and halted at line ${scriptPosition}\n    ${err}`);
        }
```

 The asynchronous errors cause the whole WoT Runtime to fail.

**Comment by mkovatsc** [comment]
Thanks for reporting!
If you have a better idea than passing decorated scheduling functions that wrap the handler in a try-catch block, please comment -- best in a new Issue at https://github.com/eclipse/thingweb.node-wot/issues.

Fixed in https://github.com/eclipse/thingweb.node-wot/commit/52a9f3618bf32db98e2bad08abd5efd58654aa72.
Closing.
