### ISSUE TITLE
Why is node-wot-servient-examples excluded from build? (no package.json)

### ISSUE THREAD

**Issue by mkovatsc** [thingweb/node-wot#20]
Complete rewrite of the issue: node-wot-servient-examples does not have a package.json, so no dist folder is created, no example can be run.

Is there a reason it was excluded?

**Comment by mkovatsc** [comment]
I guess because most of it is broken now / too much effort to port to new packages.

I will try to at least port the raspberry-servient.ts to a privileged script (depends on `require('fs')`).

**Comment by h0ru5** [comment]
Reason: Lack of resources
Those scripts are examples for constructing own servients as I've seen, they are standalone launchers and not scripts that are run in a sandbox *by* a servient -  as such they can access 'fs' normally.

What is needed is to get them up again:
* adjust imports (package names instead of paths for "our" packages)

Then you can run them with ``ts-node``. To get them transpiled as part of the build:

* copy files into src
* add package.json  that has a 'build' runner in ``script`` and dependencies on the dependencies that are not transient (maybe add ``private: true`` to avoid accidently publishing it)
* add a .tsconfig (copy from other module)

then the .js files are in the dist and runnable with plain node.

**Comment by mkovatsc** [comment]
This has become the `demo-servients` package. Closing.
