### ISSUE TITLE
Install new versions of NodeJS, e.g., on Raspberry Pi

### ISSUE THREAD

**Issue by mkovatsc** [thingweb/node-wot#94]
Using NPM, you can install NodeJS independent from the usually outdated package managers such as apt. This is nicely done by [n](https://www.npmjs.com/package/n):

```
sudo npm cache clean -f
sudo npm install -g n
```

To get the "stable" version:
```
sudo n stable
```

To get the "latest" version:
```
sudo n latest
```

Finally, make the `node` command available through:
```
sudo ln -sf /usr/local/n/versions/node/<VERSION>/bin/node /usr/bin/node
```

**Comment by mmccool** [comment]
Nice.   Much easier than the approach given on the Node.js site (downloading and running a script).

**Comment by mmccool** [comment]
Aside: make sure you update node before npm.   If you self-update npm first (eg using "npm i -g npm") you can get into a situation where npm won't run because it relies on a version of node that is not installed yet.  Guess how I know this...
Probably a temporary problem, the dependency tracker in npm *should* be preventing this situation, but...

**Comment by mkovatsc** [comment]
Moved to https://github.com/eclipse/thingweb.node-wot/issues/18.
Closing.
